services:
  - type: web
    name: plagiarism-detector-internet-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SEARCH_PROVIDER
        value: internet_server_all
      - key: ALLOW_ORIGINS
        value: '*'
